added example for iris web framework
auth0/go-jwt-middleware pull request #199
Opened 2023-05-05 12:36 UTC by mehulgohil

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### 🔧 Changes
This PR adds an example for the iris web framework

### 📚 References
[Iris](https://github.com/kataras/iris)

### 🔬 Testing

2023-05-15 15:22 UTC, ewanharris requested changes
Thanks for the PR @mehulgohil! I've just left a couple comments around consistency with other examples, but other than that this looks good!

2023-05-15 15:22 UTC, ewanharris commented on examples/iris-example/go.mod
> +
I think similar to the other examples we should add a replace here so the local version of this repo gets used


```suggestion

replace github.com/auth0/go-jwt-middleware/v2 => ./../../

```

2023-05-15 15:22 UTC, ewanharris commented on examples/iris-example/main.go
> +		ctx.JSON(http.StatusOK)
To match the other examples I think we should return `claims` here

```suggestion
		ctx.JSON(claims)
```

2023-05-16 04:43 UTC, mehulgohil commented on examples/iris-example/main.go
> +		ctx.JSON(http.StatusOK)
Resolved

2023-05-16 04:45 UTC, mehulgohil commented
Hi @ewanharris 
Resolved both the comments

2023-05-16 10:45 UTC, ewanharris approved these changes
Thanks @mehulgohil

2023-05-16 10:46 UTC, merged