jwt go validator
auth0/go-jwt-middleware pull request #91
Opened 2021-05-29 16:39 UTC by oxisto

- add v2 warning to readme
- first pass at simplifying JWT library functionality into an interface (#77)
- removing examples for now
- main middleware tests (#90)
- fix: CheckJWT clones the request (#89)
- add square/go-jose.v2 token validator (#84)
- Started validator for golang-jwt/jwt
- Custom claims work. errors are gone

2021-06-10 14:34 UTC, grounded042 commented
Hey @oxisto thanks for this! I'm a little swamped at the moment, but I'm carving out some time on Friday to review this.

2021-06-11 16:56 UTC, grounded042 commented on validate/jwt-go/jwtgo.go
> +	customClaims func() CustomClaims
nit: add `// optional options` here

2021-06-11 17:02 UTC, grounded042 commented on validate/jwt-go/jwtgo_test.go
> +		//expectedClaims	string
Could we drop this since we are not using it?

2021-06-11 17:03 UTC, grounded042 commented on validate/jwt-go/jwtgo_test.go
> +		},*/
and drop this as well

2021-06-11 17:03 UTC, grounded042 commented on validate/jwt-go/jwtgo_test.go
> +				//WithExpectedClaims(func() jwt.Expected { return testCase.expectedClaims }),
like the above we can drop this

2021-06-11 17:04 UTC, grounded042 commented on validate/jwt-go/jwtgo_test.go
> +		}*/
We could also drop this.

2021-06-11 17:09 UTC, grounded042 requested changes
Overall this looks great and thank you for the contribution! I left a couple of comments and nits on cleanups.

> It follows largely the same style as the jose one, with a few exceptions:
>    - Clock skew is not supported
>    - Expected claims can not be set

Not supporting clock skew isn't a blocker, but it is a downside here. One of the features we want to support is clock skew. Is it possible that `golang-jwt/jwt` will support this in the future?

Not supporting expected claims is no problem as that's a setup from the other package.

2021-06-11 20:42 UTC, oxisto commented
> Overall this looks great and thank you for the contribution! I left a couple of comments and nits on cleanups.
> 
> > It follows largely the same style as the jose one, with a few exceptions:
> > 
> > * Clock skew is not supported
> > * Expected claims can not be set
> 
> Not supporting clock skew isn't a blocker, but it is a downside here. One of the features we want to support is clock skew. Is it possible that `golang-jwt/jwt` will support this in the future?
> 
> Not supporting expected claims is no problem as that's a setup from the other package.

Thanks for the review, I will look at the smaller changes. I am planning to add clock skew among other validation features from the old `v4` to `golang-jwt/jwt` in a backwards compatible way (see https://github.com/golang-jwt/jwt/issues/16). Unfortunately, I do not have a dedicate time-frame for this, yet. June is quite busy here.

2021-06-11 20:57 UTC, grounded042 commented
Awesome! Knowing it's on the backlock is a big help!

2021-06-12 02:35 UTC, grounded042 approved these changes
Thanks @oxisto, this looks great!

2021-06-12 02:37 UTC, merged